"""
Django settings for Qute project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+,-./:;<=>?@[]^_`{|}~"
# 91^63, ~410bit secret key
SECRET_KEY = 'KPzQ%BJ1We^e,Zc/.Ar98h[_Rnouf!xuZ!FQ)d;/}j,d1Ml%4&IXb^X.9S6i$fc'
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: don't run with this in production!
CSRF_TRUSTED_ORIGINS = []
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "compressor",
    "captcha",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'survey.apps.SurveyConfig',
]

AUTH_USER_MODEL = 'survey.Student'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/result/'
LOGOUT_REDIRECT_URL = LOGIN_URL

MIDDLEWARE = [
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qute.urls'

#HTML_MINIFY = True
#COMPRESS_ENABLED = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qute.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = 'static/'

#STATICFILES_DIRS = [BASE_DIR / "survey/static"]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder', 
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{asctime}[{levelname}] {message}',
            'style': '{',
        },
    },    
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / r'logs/.log',
            'when': 'midnight',
            #'interval': 1,
            'backupCount': 7,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console','file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


import random
def my_challenge():
    #chars = "13456789ABCDEFGHJKLMNPQRTUVWXY"
    chars = "0123456789"
    ret = ''
    for i in range(4):
        ret += random.choice(chars)
    return ret, ret.lower()

CAPTCHA_CHALLENGE_FUNCT = my_challenge
CAPTCHA_FOREGROUND_COLOR = '#001111'
CAPTCHA_FONT_PATH = str(STATIC_ROOT/'ComicMono.ttf')

MAX_SUBMIT_COUNT = 7

def max_score(qus):
    score = 0
    for page in qus:
        for q in page:
            for c in q['choices']:
                if c['value'] > 0:
                    score += c['value']
    return score

import json
with open(BASE_DIR/r'survey/static/q-large.json',mode='r',encoding='utf8') as jfile:
    QUS_LARGE = json.loads(jfile.read())
with open(BASE_DIR/r'survey/static/q-small.json',mode='r',encoding='utf8') as jfile:
    QUS_SMALL = json.loads(jfile.read())
with open(BASE_DIR/r'survey/static/feedback.json',mode='r',encoding='utf8') as jfile:
    FEEDBACK_QUESTIONS = json.loads(jfile.read())['fbquestions']

MAX_SCORE_LARGE = max_score(QUS_LARGE)
MAX_SCORE_SMALL = max_score(QUS_SMALL)

